name: daybreak

services:
  backend:
    build:
      context: ../
      dockerfile: ./compose/backend/Dockerfile
    environment:
      DEBUG: True
      DJANGO_SECRET_KEY: django-secret-d4ybr34k
      DATABASE_HOST: postgres
      DATABASE_NAME: daybreak
      DATABASE_USER: daybreak
      DATABASE_PASSWORD: p4ssw0rd
    env_file:
      - path: ../.envs/.backend.env
        required: false
    ports:
      - 8001:8001
    volumes:
      - type: bind
        source: ./backend/entrypoint.sh
        target: /bin/entrypoint.sh
      - type: bind
        source: ../backend
        target: /app
    depends_on:
      - postgres
      - redis
    command: /bin/entrypoint.sh

  frontend:
    image: node:25-alpine
    env_file:
      - path: ../.envs/.frontend.env
        required: false
    ports:
      - 3030:3000
    volumes:
      - type: bind
        source: ../frontend
        target: /app
    depends_on:
      - backend
    working_dir: /app
    command: yarn run dev

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: daybreak
      POSTGRES_USER: daybreak
      POSTGRES_PASSWORD: p4ssw0rd
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init/:/docker-entrypoint-initdb.d/

  redis:
    image: redis:8
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  postgres_data: {}
  redis_data: {}